"""Hello ps_example!

Revision ID: 21a5ce4212b
Revises: None
Create Date: 2015-04-06 16:01:19.624619

"""

# revision identifiers, used by Alembic.
revision = '21a5ce4212b'
down_revision = None

import sqlalchemy as sa

import sacrud
import pyramid_elfinder
from alembic import op


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_name', sa.Unicode(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('test_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sacrud.exttype.FileStore(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mptt_pages',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sacrud.exttype.SlugType(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('in_menu', sa.Boolean(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('redirect_type', sacrud.exttype.ChoiceType(), nullable=True),
    sa.Column('seo_title', sa.String(), nullable=True),
    sa.Column('seo_keywords', sa.String(), nullable=True),
    sa.Column('seo_description', sa.String(), nullable=True),
    sa.Column('seo_metatags', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redirect_page', sa.Integer(), nullable=True),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['mptt_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['redirect_page'], ['mptt_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('mptt_pages_level_idx', 'mptt_pages', ['level'], unique=False)
    op.create_index('mptt_pages_lft_idx', 'mptt_pages', ['lft'], unique=False)
    op.create_index('mptt_pages_rgt_idx', 'mptt_pages', ['rgt'], unique=False)
    op.create_table('test_deform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filestore', sacrud.exttype.FileStore(), nullable=True),
    sa.Column('filestore2', sacrud.exttype.FileStore(), nullable=True),
    sa.Column('filestore3', sacrud.exttype.FileStore(), nullable=True),
    sa.Column('choice', sacrud.exttype.ChoiceType(), nullable=True),
    sa.Column('guid', sacrud.exttype.GUID(), nullable=True),
    sa.Column('enum', sa.Enum(u'IPv6', u'IPv4', name='ip_type'), nullable=True),
    sa.Column('elfinder', pyramid_elfinder.models.ElfinderString(), nullable=True),
    sa.Column('foo', sa.String(), nullable=True),
    sa.Column('slug', sacrud.exttype.SlugType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_bool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('middlename', sa.Unicode(), nullable=False),
    sa.Column('surname', sa.Unicode(), nullable=False),
    sa.Column('user_password', sa.String(length=256), nullable=True),
    sa.Column('registered_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_login_date', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('user_name', sa.Unicode(length=30), nullable=True),
    sa.Column('email', sa.Unicode(length=100), nullable=False),
    sa.Column('security_code', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('test_customizing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('name_fr', sa.String(), nullable=True),
    sa.Column('name_bg', sa.String(), nullable=True),
    sa.Column('name_cze', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description2', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('in_menu', sa.Boolean(), nullable=True),
    sa.Column('in_banner', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_union',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('foo', sa.Boolean(), nullable=True),
    sa.Column('cash', sa.Integer(), nullable=True),
    sa.Column('double_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foo', sa.String(), nullable=True),
    sa.Column('ufoo', sa.Unicode(), nullable=True),
    sa.Column('fooText', sa.Text(), nullable=True),
    sa.Column('ufooText', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_permissions',
    sa.Column('perm_name', sa.Unicode(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perm_name', 'user_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('groups_permissions',
    sa.Column('perm_name', sa.Unicode(length=30), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perm_name', 'group_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('resources',
    sa.Column('resource_name', sa.Unicode(length=100), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_group_id', sa.Integer(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.Unicode(length=30), nullable=False),
    sa.ForeignKeyConstraint(['owner_group_id'], ['groups.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['resources.resource_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resources_owner_group_id'), 'resources', ['owner_group_id'], unique=False)
    op.create_index(op.f('ix_resources_owner_user_id'), 'resources', ['owner_user_id'], unique=False)
    op.create_table('external_identities',
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('alt_token', sa.String(length=255), nullable=True),
    sa.Column('external_user_name', sa.Unicode(length=255), nullable=True),
    sa.Column('local_user_name', sa.Unicode(length=50), nullable=False),
    sa.Column('provider_name', sa.Unicode(length=50), nullable=False),
    sa.Column('external_id', sa.Unicode(length=255), nullable=False),
    sa.Column('token_secret', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['local_user_name'], ['users.user_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('local_user_name', 'provider_name', 'external_id')
    )
    op.create_table('test_all_types',
    sa.Column('col_pk', sa.Integer(), nullable=False),
    sa.Column('col_bigint', sa.BigInteger(), nullable=True),
    sa.Column('col_boolean', sa.Boolean(), nullable=True),
    sa.Column('col_date_time', sa.Date(), nullable=True),
    sa.Column('col_date', sa.DateTime(), nullable=True),
    sa.Column('col_date2', sa.DateTime(), nullable=True),
    sa.Column('col_enum', sa.Enum(u'IPv6', u'IPv4', name='ip_type'), nullable=True),
    sa.Column('col_choice', sacrud.exttype.ChoiceType(), nullable=True),
    sa.Column('col_float', sa.Float(), nullable=True),
    sa.Column('fk_test_alltypes', sa.Integer(), nullable=True),
    sa.Column('fk_test_union', sa.Integer(), nullable=True),
    sa.Column('col_elfinder', pyramid_elfinder.models.ElfinderString(), nullable=True),
    sa.Column('col_guid', sacrud.exttype.GUID(), nullable=True),
    sa.Column('col_integer', sa.Integer(), nullable=True),
    sa.Column('col_numeric', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('col_string', sa.String(), nullable=True),
    sa.Column('col_text', sa.Text(), nullable=True),
    sa.Column('col_unicode', sa.Unicode(), nullable=True),
    sa.Column('col_unicode_text', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['fk_test_alltypes'], ['test_all_types.col_pk'], ),
    sa.ForeignKeyConstraint(['fk_test_union'], ['test_union.id'], ),
    sa.PrimaryKeyConstraint('col_pk')
    )
    op.create_table('users_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users_resources_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('perm_name', sa.Unicode(length=50), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', 'perm_name'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('groups_resources_permissions',
    sa.Column('perm_name', sa.Unicode(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perm_name', 'resource_id', 'group_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups_resources_permissions')
    op.drop_table('users_resources_permissions')
    op.drop_table('users_groups')
    op.drop_table('test_all_types')
    op.drop_table('external_identities')
    op.drop_index(op.f('ix_resources_owner_user_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_owner_group_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('groups_permissions')
    op.drop_table('users_permissions')
    op.drop_table('test_text')
    op.drop_table('test_union')
    op.drop_table('test_customizing')
    op.drop_table('users')
    op.drop_table('test_bool')
    op.drop_table('test_deform')
    op.drop_index('mptt_pages_rgt_idx', table_name='mptt_pages')
    op.drop_index('mptt_pages_lft_idx', table_name='mptt_pages')
    op.drop_index('mptt_pages_level_idx', table_name='mptt_pages')
    op.drop_table('mptt_pages')
    op.drop_table('test_file')
    op.drop_table('groups')
    ### end Alembic commands ###
